sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t josse995/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true josse995/docker-react yarn test
